/* ==========================================================================
   KAVARI — Diccionario FRANCÉS (fr)
   Se carga DESPUÉS de js/idioma.js y se integra mediante
   window.__kavariIdiomasExtras (ver lógica en js/idioma.js).
   Las claves que falten usan el fallback automático: fr → en → es.
   ========================================================================== */
if (!window.__kavariIdiomasExtras) window.__kavariIdiomasExtras = {};
window.__kavariIdiomasExtras.fr = {

  /* ─── Navegación ─── */
  navInicio: 'Accueil',
  navDestinos: 'Destinations',
  navRegistrarmeGuia: 'Devenir guide',
  sobrenosotros: 'À propos',
  ayuda: 'Aide',
  contacto: 'Contact',
  tutorial: 'Tutoriel',
  modoOscuro: 'Sombre',

  /* ─── Footer ─── */
  footerLinksTitle: 'Liens rapides',
  footerLinkInicio: 'Accueil',
  footerLinkDestinos: 'Destinations',
  footerLinkSobre: 'À propos',
  footerLinkGuias: 'Guides locaux',
  footerLinkContacto: 'Contact',
  footerNewsTitle: 'Newsletter',
  footerNewsSub: 'Recevez offres et actualités de voyage.',
  footerNewsLabel: 'Votre courriel',
  footerNewsPlaceholder: 'tu@exemple.com',
  footerNewsBtn: "S'abonner",
  footerNewsOk: 'Merci !',
  footerTexto: '© 2025 Kavari — Tous droits réservés.',
  footerPrivacidad: 'Politique de confidentialité',
  footerTerminos: 'Conditions générales',
  footerCookies: 'Politique de cookies',
  footerSub1: 'Votre prochaine aventure commence ici.',

  /* ─── Botones y etiquetas comunes ─── */
  volverAtras: 'Retour',
  verMas: 'Voir plus',
  desde: 'À partir de',
  porPersona: 'par personne',
  porNoche: 'par nuit',
  verDetalles: 'Voir les détails',
  quieroIr: 'Je veux y aller',
  verDestinoCompleto: 'Voir la destination complète',
  reservarAhora: 'Réserver maintenant',
  verTodosLosProductos: 'Voir tous les produits',
  articulos: 'articles',
  reviewsLabel: 'avis',
  reservarEstadia: "Voir les options dans la zone",
  zonaLabel: 'Zone',
  seleccionaPais: 'Choisis un pays',
  itinerarioSugerido: 'Itinéraire suggéré',
  paqueteModalIncluye: 'Que comprend le forfait ?',

  /* ─── Etiquetas y regiones de forfaits ─── */
  tagPopular: 'Populaire',
  tagAventura: 'Aventure',
  tagCultural: 'Culturel',
  tagClasico: 'Classique',
  tagLocal: 'Local',
  tagOferta: 'Offre',
  regionEuropa: 'Europe',
  regionAsia: 'Asie',
  regionCentroamerica: 'Amérique centrale',
  regionSudamerica: 'Amérique du Sud',
  regionCaribe: 'Caraïbes',
  regionNorteamerica: 'Amérique du Nord',
  featureVuelo: 'Vol inclus',
  featureHotel4: 'Hôtel 4 étoiles',
  featureHotel3: 'Hôtel 3 étoiles',
  featureDias4: '4 jours / 3 nuits',
  featureDias5: '5 jours / 4 nuits',
  featureDias6: '6 jours / 5 nuits',
  featureDias8: '8 jours / 7 nuits',
  featureDias9: '9 jours / 8 nuits',
  featureDias10: '10 jours / 9 nuits',
  featureGuia: 'Guide certifié',
  featureTransporte: 'Transport local',
  featureTours: 'Visites quotidiennes',
  featureTraslados: 'Transferts inclus',
  featureActividades: 'Activités incluses',

  /* ─── Page Destinations (paises) ─── */
  paisesSub: '21 pays à ta disposition',
  paisesContinenteTodos: 'Tous',
  paisesContinenteAmerica: 'Amérique',
  paisesContinenteCaribe: 'Caraïbes',
  paisesContinenteEuropa: 'Europe',
  paisesContinenteAsia: 'Asie',
  paisesContinenteAfrica: 'Afrique',

  /* ─── Index / héros ─── */
  heroTitulo: 'Explore le monde avec KAVARI',
  heroExplorarDestinos: 'Explorer les destinations',
  losDestinosQueDefinen: 'Les destinations qui définissent',

  /* ─── Sections du pays (destino.html) ─── */
  navPaises: 'Lieux',
  navCultura: 'Culture',
  navDestinos2: 'Destinations',
  navGastronomia: 'Gastronomie',
  navAventura: 'Aventure',
  navPractica: 'Infos pratiques',
  navAerolineas: 'Compagnies',
  navHospedajes: 'Hébergement',
  navSouvenirs: 'Souvenirs',
  navGuias: 'Guides',
  culturaTag: 'Culture',
  culturaTitulo: 'Culture et traditions',
  culturaDesc: "Découvre l'âme du pays à travers ses coutumes.",
  lugaresTag: 'Lieux',
  gastronomiaTag: 'Gastronomie',
  gastronomiaTitulo: 'Saveurs du pays',
  gastronomiaDesc: 'Les plats incontournables de sa cuisine.',
  aventuraTitulo: 'Aventure et nature',
  aventuraDesc: 'Activités pour les amants des sensations fortes.',
  practicaTag: 'Pratique',
  practicaTitulo: 'Conseils pratiques',
  practicaDesc: 'Tout ce qu’il faut savoir avant de voyager.',
  aerolineasTitulo: 'Compagnies aériennes qui desservent le pays',
  aerolineasDesc: 'Compare les options pour arriver à destination.',
  hospedajesTitulo: 'Hébergements recommandés',
  hospedajesDesc: 'Références par zone : des quartiers larges pour choisir où loger.',
  hospedajesZonaNota: "Nous n'affichons pas de propriétés exactes : chaque carte représente une zone. En continuant, tu verras toutes les vraies options disponibles sur Airbnb dans cette zone.",
  souvenirsTitulo: 'Souvenirs et boutiques',
  souvenirsDesc: 'Rapporte un morceau du pays avec toi.',
  guiasSectionTitle: 'Guides locaux certifiés',
  rankOro: 'Or',
  rankPlata: 'Argent',
  rankDiamante: 'Diamant',

  /* ─── Chatbot ─── */
  chatTitle: 'Assistant KAVARI',
  chatSubtitle: 'Ton guide de voyage',
  chatInputPlaceholder: 'Écris ta question…',
  chatWelcomeGeneral: "👋 Bonjour ! Je suis l'assistant KAVARI. Pose-moi tes questions sur les destinations, forfaits ou comment planifier ton prochain voyage.",

  /* ─── Compte / authentification ─── */
  perfilGoogleBtn: 'Continuer avec Google',
  perfilGithubBtn: 'Continuer avec GitHub',
  perfilOtpEnviar: 'Envoyer le code',
  perfilOtpVerificar: 'Vérifier le code',
  perfilTelefono: 'Téléphone',
  perfilGuardar: 'Enregistrer',
  perfilEliminarCuenta: 'Supprimer le compte',
  perfilFavoritosQuitar: 'Retirer des favoris',
  cuentaBtnIngresar: 'Se connecter',
  cuentaBtnCrear: 'Créer un compte',
  cuentaNombreLabel: 'Nom complet',
  cuentaPassLabel: 'Mot de passe',
  cuentaCorreoPlaceholder: 'ton@courriel.com',
  cuentaPassVer: 'Afficher',
  cuentaCerrarSesion: 'Se déconnecter',
  cuentaTerminos: "J'accepte les conditions générales et la politique de confidentialité",

  /* ─── Contact ─── */
  contactoEyebrow: 'Parlons-en',
  contactoTitulo: 'Contact',
  contactoSubtitulo: 'Retrouve-nous sur les réseaux sociaux ou écris-nous directement.',
  contactoEscribenos: 'Écris-nous',
  contactoSuperate: 'Centre Supérate David',
  contactoCorreo: 'Courriel',

  /* ─── Aide ─── */
  tituloAyuda: 'Aide · KAVARI',
  ayudaBadge: 'Centre daide',
  ayudaTitulo: 'Comment pouvons-nous taider ?',
  ayudaSubtitulo: 'Trouve des réponses rapides sur le fonctionnement de KAVARI.',
  ayudaBuscar: 'Rechercher une question…',
  catViajeros: 'Voyageurs',
  catGuias: 'Guides',
  catPlataforma: 'Plateforme',
  catPaquetes: 'Forfaits',
  ayudaLimpiar: 'Effacer',
  ayudaPasosTitulo: 'Commence en 3 étapes',
  ayudaPaso1Titulo: '1. Explore les destinations',
  ayudaPaso1Desc: 'Parcours les 21 pays et découvre culture, gastronomie, aventure, compagnies et hébergements de chaque destination.',
  ayudaPaso2Titulo: '2. Planifie avec notre IA',
  ayudaPaso3Titulo: '3. Réserve et pars',
  ayudaExpandir: 'Déplier',
  ayudaCopiar: 'Copier',

  /* ─── Forfaits (planes) ─── */
  planesNavPlanes: 'Forfaits',
  planPremiumDuracion: '12 mois',
  footerLinkDestinos: "Destinations",
  footerLinkContacto: "Contact",
  navDestinos: "Destinations",
  contacto: "Contact",
  ayudaAtajoIA: "Ask the assistant",
  navCultura: "Culture",
  navDestinos2: "Destinations",
  paisesContinenteEuropa: "Europe",
  aboutComunicacion: "Communication",
  aboutDisenadora: "Designer",
  aboutDiseno: "Design",
  ayudaPaso2Desc: "Ask about the weather, visas, safety, costs and transport with the assistant specialised in each country.",
  ayudaPaso3Desc: "Book flights and hotels, hire certified guides or write to us to build your complete package.",
  ayudaAtajosTitulo: "Quick access",
  ayudaAtajoDestinos: "Explore destinations",
  ayudaAtajoGuias: "See tour guides",
  ayudaAtajoTutorial: "Start the tutorial",
  faqViajerosTitulo: "FAQ — Travellers",
  faq1q: "How do I search for a destination on KAVARI?",
  faq1a: "On the Destinations page you will find the 21 countries available on KAVARI. Use the search bar at the top to filter by country or city name. Click “View destination” to access all the tourist information for that country: culture, gastronomy, adventure, airlines, accommodation and more.",
  faq2q: "Can I hire a tour guide through KAVARI?",
  faq2a: "Yes. Within each country page you will find the “Tour Guides” section listing the certified guides available for that destination. Filter by level (Diamond, Gold, Silver) and click “Hire” to send your request directly to the guide.",
  faq3q: "Are the prices shown final?",
  faq3a: "Airline and accommodation prices are reference prices for mid-season. Final prices may vary depending on dates, availability and flight origin. When you click “Book flight” or “See options in the area”, you will be redirected directly to the airline or Airbnb listing to confirm the final price.",
  faq4q: "What practical information can I find about each country?",
  faq4a: "In the “Practical info” section of each country you will find: local currency, official language, visas and required documents, transport, Wi-Fi connectivity, best seasons to travel and a suggested itinerary. You can also use the AI Assistant to ask specific questions about the destination.",
  faq5q: "How does the KAVARI AI Assistant work?",
  faq5a: "Each country page has a chatbot specialised in that destination. You can ask it about weather, visas, safety, gastronomy, costs, transport, emergencies and more. The assistant answers with information specific to the selected country. Use the preset suggestions to start or type your own question.",
  faqGuiasTitulo: "FAQ — Tour guides",
  faq6q: "How do I register as a tour guide on KAVARI?",
  faq6a: "Click the “I'm a Guide” button on the home page or visit the Guides section and select “Join as a guide”. Complete your profile with your name, description, languages, specialties, and the city and country where you work. Choose your membership level (Silver, Gold or Diamond) and make the payment to activate your profile.",
  faq7q: "What are the differences between the Silver, Gold and Diamond levels?",
  faq7a: "<strong>Silver ($20/month):</strong> Standard visibility in guide listings. <br><strong>Gold ($35/month):</strong> Higher ranking in search results, featured profile. <br><strong>Diamond ($50/month):</strong> Top priority in listings, special badge, appears first to travellers. Diamond and Gold guides are listed ahead of Silver guides.",
  faq8q: "In which countries can I register as a guide?",
  faq8a: "You can register as a guide for any of the 21 destinations available on KAVARI. When you select your country during registration, your profile will automatically appear in that country's “Tour Guides” section. If you operate in several countries, you can create separate profiles for each one.",
  faq9q: "What payment methods does KAVARI accept?",
  faq9a: "To pay for guide memberships we accept: Yappy (Panama mobile banking), bank transfer (Banco General, BAC, Banistmo) and credit/debit card (Visa, Mastercard, American Express). All payments are protected with SSL encryption.",
  faqPlataformaTitulo: "FAQ — The platform",
  faq10q: "Which languages is KAVARI available in?",
  faq10a: "KAVARI is available in Spanish, English, Portuguese and French. You can change the language at any time using the language selector (🌐 icon) in the navigation bar of every page. Your preference is saved automatically for your next visit.",
  faq11q: "How do I activate dark mode?",
  faq11a: "Click the 🌙 icon on any KAVARI navigation bar to activate dark mode. You can also tap the ☀️ icon to switch back to light mode. Your preference is saved automatically and applied across all pages of the platform.",
  faq12q: "How does the platform tutorial work?",
  faq12a: "The interactive tutorial appears automatically the first time you visit KAVARI. It guides you step by step through all the platform's features with pop-up messages, arrows and examples. To watch it again, click the “Tutorial” button in the main menu of the home page.",
  faqPaquetesTitulo: "FAQ — Travel packages",
  faq13q: "What does a KAVARI travel package include?",
  faq13a: "Every package is different, but they generally include: international flight (on international packages), 3- or 4-star hotel, airport-hotel transfers, certified tour guide, daily breakfast and entrance to the main attractions. Click “View details” on any package to see exactly what that itinerary includes.",
  faq14q: "Can I book directly from KAVARI?",
  faq14a: "KAVARI currently works as an information platform and travel directory. When you click “Book now” you will be taken to the full destination page to coordinate with local guides. For flight and hotel bookings, links take you directly to the airlines and to Airbnb. For full packages, contact us through the Contact form.",
  ayudaNoResultados: "No questions matched your search.",
  ayudaCTATitulo: "Didn't find what you were looking for?",
  ayudaCTADesc: "Our team is ready to help you with any question about destinations, guides or the platform.",
  ayudaCTAContacto: "Contact support",
  ayudaCTAGuias: "See tour guides",
  tituloContacto: "Contact — KAVARI",
  metaDescContacto: "Contact KAVARI: social media, email addresses and more information about our project at Centro Supérate David.",
  contactoTitulo: "Contact",
  contactoFloatTitulo: "We are here to help you",
  contactoFloatDesc: "Connect with the KAVARI team through our social media or by email.",
  contactoRedes: "Social media",
  contactoDestinosLabel: "Destinations and adventures",
  contactoComunidad: "Traveller community",
  contactoGuiasCert: "Certified tour guides",
  contactoTips: "Travel tips and advice",
  contactoNoticias: "News and updates",
  contactoSede: "Our headquarters",
  contactoFundacion: "Fundación Emanuel González-Revilla",
  contactoPromo: "Programa Supérate — Chiriquí Province",
  contactoUbicacion: "Location",
  contactoUbicacionVal: "Centro Supérate David, Chiriquí, Panama",
  contactoPromocion: "Cohort",
  contactoProyecto: "Project",
  contactoProyectoVal: "KAVARI was created as part of the technology programme at Centro Supérate David, with the goal of applying digital skills to a social-impact project.",
  contactoCorreoPrincipal: "Main email – General enquiries",
  contactoEquipoLabel: "KAVARI Team",
  contactoFormTitulo: "Contact form",
  contactoFormEncabezado: "Send us a message",
  contactoFormIntro: "Tell us about your enquiry and the KAVARI team will get back to you shortly.",
  contactoNombreLabel: "Full name",
  contactoNombrePlaceholder: "Your name",
  contactoEmailPlaceholder: "you@example.com",
  contactoAsuntoLabel: "Subject",
  contactoMensajeLabel: "Message",
  contactoMensajePlaceholder: "Write your message here…",
  contactoEnviar: "Send message",
  contactoVolver: "Back to home",
  tituloCuenta: "My account · KAVARI",
  cuentaTitulo: "Your next adventure starts here.",
  cuentaDesc: "Save your plan and keep exploring KAVARI from the same device.",
  cuentaP1: "Local plan and preferences",
  cuentaP2: "Direct access to your plans",
  cuentaP3: "No payments in this demo",
  tituloDestino: "Destination — KAVARI Travel",
  seleccionarPais: "Country",
  buscarPais: "Search country…",
  heroContinente: "Your next destination",
  heroSubtitulo: "with KAVARI",
  heroDesc: "Journeys that transform, experiences that last.",
  heroVerVuelosDisponibles: "See available flights",
  scrollDesplazar: "Scroll",
  destinosDestacadosTitulo: "Featured destinations",
  quoteInicio: "Travel is the only investment that makes you richer.",
  citeInicio: "KAVARI · 2025 Guide",
  iconosCultura: "Cultural icons",
  lugaresTitulo: "Must-see destinations",
  lugaresDesc: "Discover the places that define every corner of the world.",
  aventuraTag: "Nature · Adrenaline",
  seleccionEditorial: "Editor's selection",
  experienciasAventura: "Adventure-defining experiences",
  descAventura: "Activities for every adrenaline level.",
  quotePractica: "The best destinations aren't always the best known.",
  citePractica: "KAVARI · 2025 Guide",
  aerolineasTag: "Flights · International connections",
  aerolineasIntro: "Reference economy-class prices. Final prices vary by date, availability and origin. Click 'Book flight' to go straight to the airline.",
  hospedajesTag: "Stay · Airbnb",
  hospedajesIntro: "A selection of Airbnb stays. Prices per night in mid-season. Click 'See options in the area' to go straight to the offer on Airbnb.",
  souvenirsTag: "Handicrafts · Local culture",
  guiasTag: "Local experts · Certified",
  guiasTituloHeader: "Tour Guides",
  guiasDescHeader: "Connect with certified local experts who know every corner of the destination.",
  modalCerrar: "Close",
  verEnGoogleMaps: "View on Google Maps",
  tituloIndex: "KAVARI Travel — Discover the World",
  heroDescripcion: "Live unforgettable experiences around the world.",
  searchTitulo: "Ready for your next adventure?",
  searchDescripcion: "Find the perfect destination and start travelling.",
  searchBoton: "Start now",
  top10Titulo: "Top 10 Most Visited Places",
  paquetesTitulo: "Travel Packages",
  planCtaEyebrow: "Personalised advice",
  planCtaTitulo: "Request your travel plan",
  planCtaDesc: "Tell us your dream and a KAVARI advisor will design a tailor-made plan, free of charge.",
  planCtaNombreLabel: "Full name",
  planCtaNombrePH: "E.g.: Ana Torres",
  planCtaEmailLabel: "Email address",
  planCtaEmailPH: "you@email.com",
  planCtaTelefonoLabel: "Phone",
  planCtaDestinoLabel: "Destination of interest",
  planCtaDestinoOpc: "Select a destination",
  planCtaDestinoOtro: "Other destination",
  planCtaFechaLabel: "Travel date",
  planCtaViajerosLabel: "Number of travellers",
  planCtaPresupuestoLabel: "Estimated budget per person (USD)",
  planCtaPresupuestoOpc: "Select a range",
  planCtaMensajeLabel: "Tell us about your trip (optional)",
  planCtaMensajePH: "Type of trip, interests, flexible dates…",
  planCtaBoton: "Send request",
  tituloPaises: "KAVARI – Explore 21 Destinations in Latin America and the Caribbean",
  paisesEyebrow: "Your Next Adventure Awaits",
  paisesTitulo: "Explore Our Destinations",
  paisesBuscar: "Search your destination with Kavari…",
  paisesDestinos: "destinations",
  paisesCargando: "Loading destinations...",
  tituloPerfil: "My Profile · KAVARI",
  perfilAuthTitulo: "Log in to see your profile",
  perfilAuthDesc: "Access your account to manage your information and travel preferences.",
  perfilOtpLink: "Send verification code by email",
  perfilOtpEmailLabel: "Email address",
  perfilOtpCodeLabel: "Verification code",
  perfilNoCuenta: "Don't have an account?",
  perfilCrearCuenta: "Create account",
  perfilRegistroTitulo: "Create your KAVARI account",
  perfilRegistroDesc: "Sign up to save your preferences and unlock exclusive features.",
  perfilYaCuenta: "Already have an account?",
  perfilIniciarSesion: "Log in",
  perfilTabInfo: "Personal information",
  perfilTabViaje: "Travel preferences",
  perfilTabFavoritos: "Favourites",
  perfilTabConfig: "Settings",
  perfilFechaNacimiento: "Date of birth",
  perfilPaisResidencia: "Country of residence",
  perfilDestinosInteres: "Destinations of interest",
  perfilPresupuesto: "Monthly travel budget",
  perfilEstiloViaje: "Travel style",
  perfilIdiomasViaje: "Languages you speak",
  perfilFavoritosTitulo: "My favourite countries",
  perfilFavoritosDesc: "The countries you “liked” are saved here in your account.",
  perfilFavoritosDrag: "Drag the cards to change the order",
  perfilFavoritosSortLabel: "Sort by",
  perfilFavoritosSortAlpha: "Alphabetical",
  perfilFavoritosSortRecent: "Most recent",
  perfilFavoritosVacio: "You don't have favourite countries yet. Explore the destinations and “like” the ones you like most.",
  perfilFavoritosExplorar: "Explore destinations",
  perfilConfigCuenta: "Account",
  perfilConfigEmail: "Email address",
  perfilConfigPlan: "Current plan",
  perfilConfigPreferencias: "Preferences",
  perfilConfigIdioma: "Language",
  perfilConfigTema: "Dark mode",
  perfilConfigZona: "Danger zone",
  tituloPlanes: "Plans · KAVARI",
  planesTitulo: "Choose how you want<br>to travel with KAVARI.",
  planesDesc: "Start free or unlock planning tools and exclusive experiences.",
  planViajeroNombre: "Traveller",
  planViajeroPrecio: "Free",
  planViajeroDuracion: "forever",
  planViajeroDesc: "The simple way to discover the world with KAVARI.",
  planViajeroCta: "Continue free",
  planViajeroF1: "21 destinations",
  planViajeroF2: "Guides, culture and gastronomy",
  planViajeroF3: "KAVARI Assistant",
  planViajeroF4: "Advanced favourites",
  planPremiumBadge: "Most chosen",
  planPremiumDesc: "For those who want to prepare every detail of their next trip.",
  planPremiumCta: "Choose Premium",
  planPremiumF1: "Everything in Traveller",
  planPremiumF2: "Unlimited routes and favourites",
  planPremiumF3: "Saved travel preferences",
  planPremiumF4: "Personalised recommendations",
  planOpDesc: "The full experience for travellers who want to go one step further.",
  planOpCta: "Choose OP",
  planOpF1: "Everything in Premium",
  planOpF2: "Priority itineraries",
  planOpF3: "Early access to new features",
  planOpF4: "Priority support",
  planesNota: "Premium and OP plans can be selected from now on; charging is activated once the payment gateway is connected.",
  tituloSobrenosotros: "About Us — KAVARI",
  aboutEyebrow: "About Us",
  aboutTagline: "Connecting travellers with the world from Panama",
  aboutQueEs: "What is KAVARI?",
  aboutDesc1: "KAVARI is a smart tourism digital platform that connects travellers with real information, certified guides and destinations around the world. Our mission is to make planning a trip a simple, reliable and exciting experience.",
  aboutDesc2: "We were born from the idea that travelling shouldn't be complicated. With KAVARI, users have access to up-to-date information on destinations, airlines, accommodation, gastronomy, culture and much more, all in one place.",
  aboutStatDestinos: "Destinations",
  aboutStatEquipo: "Members",
  aboutStatFundacion: "Foundation",
  aboutMisionLabel: "Our Mission",
  aboutMision: "Mission",
  aboutMisionText: "To facilitate access to quality tourism information, connecting travellers with certified local guides and providing digital tools that transform the way the world moves, in a safe, accessible and exciting way.",
  aboutVisionLabel: "Our Vision",
  aboutVision: "Vision",
  aboutVisionText: "To become the leading smart tourism platform in Latin America, recognised for the quality of its information, the authenticity of its experiences and the positive impact it generates in the local communities of each destination.",
  aboutEquipo: "Our Team",
  aboutEquipoDesc: "The people who make KAVARI possible, with dedication and teamwork.",
  aboutLider: "Developer & Lead",
  aboutLiderBadge: "Project Lead",
  aboutControl: "Product Control",
  aboutGestion: "Management",
  aboutProgramador: "Developer",
  aboutDesarrollo: "Development",
  aboutPresentadora: "Presenter",
  aboutPresentador: "Presenter",
  cargandoGuias: "Loading guides…",
  filtroTodos: "All",
  contactGuide: "Contact guide",
  sinGuias: "No guides available for this destination",
  guiaDisponible: "Guide available",
  guiaNoDisponible: "Guide not available",
  contratar: "Hire",
  precioHora: "per hour",
  aerolineasNoDisponible: "No airlines available for this destination",
  reservarVuelo: "Book flight",
  hospedajesNoDisponible: "No accommodation available for this destination",
  zonaLabel: "Zone",
  cargandoTiendas: "Loading shops…",
  souvenirsTiendasLabel: "shops",
  souvenirsProductosLabel: "products",
  verEnMapa: "View on the map",
  destinosDestacadosEn: "Featured destinations in",
  explorarMas: "Explore more",
  datosSobre: "Facts about",
  culturaDarkBandTag: "Identity · Tradition",
  destinosImprescindiblesEn: "Must-see destinations in",
  aventuraDarkBandTag: "Nature · Adrenaline",
  cuandoViajar: "When to travel",
  entradaLabel: "Entrance",
  horarioLabel: "Hours",
  consejoLabel: "Tip",
  cuentaHola: "Hello, {name}",
  cuentaActiva: "Your account is active on this browser.",
  cuentaPasajero: "Passenger",
  cuentaCorreo: "Email",
  cuentaGestionar: "Manage plan →",
  cuentaUnete: "Join KAVARI",
  cuentaInicia: "Log in",
  cuentaCreaDesc: "Create a local account to keep your plan.",
  cuentaAccedeDesc: "Sign in with your name and email on this device.",
  cuentaCrearTab: "Create account",
  cuentaIngresarTab: "Log in",
  cuentaNombrePlaceholder: "As shown on your profile",
  cuentaPassPlaceholder: "At least 6 characters",
  ayudaCopiado: "Copied!",
  ayudaResultados: "questions found",
  guideErrorCargarPaises: "The countries could not be loaded.",
  guideRequeridos: "All fields are required",
  guideCorreoInvalido: "Enter a valid email address",
  guideFaltaHistorial: "You must upload your criminal record",
  guideAceptaTerminos: "You must accept the Terms and Conditions",
  guideProcesando: "Processing your registration...",
  guideSubiendoDocs: "Uploading documents...",
  guideError: "Error submitting your registration. Please try again.",
  guideExito: "Registration successful! We will contact you by email to activate your profile.",
  chatWelcomeDestino: "Hi! I'm your KAVARI assistant for <strong>{nombre}</strong>. Pick a question or type your own.",
  chatSubtitleDestino: "Specialised in {nombre}",
  contactoInstagram: 'Instagram',
  contactoPromocionVal: 'Supérate Promo 2027',
  planCtaTelefonoPH: '+507 6000-0000',
  planCtaViajerosPH: '2',
  planCtaPresupuestoBajo: '500 $ – 1 000 $',
  planCtaPresupuestoMedio: '1 000 $ – 2 500 $',
  planCtaPresupuestoAlto: '2 500 $ – 5 000 $',
  planCtaPresupuestoPremium: '5 000 $ +',
  perfilFavoritosSortManual: 'Manuel',
  planPremiumNombre: 'Premium',
  planPremiumPrecio: '9,99 $US',
  planOpNombre: 'OP',
  planOpPrecio: '19,99 $US'
};

