// Fragmento 1: mapa explicito de gaps (185 claves) -> frances
const GAPS = {
  "footerLinkDestinos": "Destinations",
  "footerLinkContacto": "Contact",
  "navDestinos": "Destinations",
  "contacto": "Contact",
  "ayudaAtajoIA": "Demander à l'assistant",
  "navCultura": "Culture",
  "navDestinos2": "Destinations",
  "paisesContinenteEuropa": "Europe",
  "aboutComunicacion": "Communication",
  "aboutDiseno": "Conception",
  "ayudaAtajosTitulo": "Accès rapide",
  "ayudaAtajoDestinos": "Explorer les destinations",
  "faq3q": "Les prix affichés sont-ils définitifs ?",
  "faq4q": "Quelles informations pratiques puis-je trouver sur chaque pays ?",
  "faq5q": "Comment fonctionne l'assistant IA de KAVARI ?",
  "faq6q": "Comment m'inscrire comme guide touristique sur KAVARI ?",
  "faq8q": "Dans quels pays puis-je m'inscrire comme guide ?",
  "faq9q": "Quels moyens de paiement KAVARI accepte-t-il ?",
  "faq11q": "Comment activer le mode sombre ?",
  "faq12q": "Comment fonctionne le tutoriel de la plateforme ?",
  "faq13q": "Que comprend un forfait de voyage KAVARI ?",
  "faq14q": "Puis-je réserver directement depuis KAVARI ?",
  "ayudaCTATitulo": "Vous n'avez pas trouvé ce que vous cherchiez ?",
  "ayudaCTAContacto": "Contacter le support",
  "tituloContacto": "Contact — KAVARI",
  "contactoTitulo": "Contact",
  "contactoFloatTitulo": "Nous sommes là pour vous aider",
  "contactoGuiasCert": "Guides touristiques certifiés",
  "contactoTips": "Conseils et astuces de voyage",
  "contactoNoticias": "Nouveautés et mises à jour",
  "contactoSede": "Notre siège",
  "contactoUbicacion": "Emplacement",
  "contactoUbicacionVal": "Centro Supérate David, Chiriquí, Panama",
  "contactoProyecto": "Projet",
  "contactoEquipoLabel": "Équipe KAVARI",
  "contactoFormTitulo": "Formulaire de contact",
  "contactoFormEncabezado": "Envoyez-nous un message",
  "contactoNombreLabel": "Nom complet",
  "contactoNombrePlaceholder": "Votre nom",
  "contactoAsuntoLabel": "Sujet",
  "contactoMensajeLabel": "Message",
  "contactoMensajePlaceholder": "Écrivez votre message ici…",
  "contactoEnviar": "Envoyer le message",
  "contactoVolver": "Retour à l'accueil",
  "tituloCuenta": "Mon compte · KAVARI",
  "cuentaTitulo": "Votre prochaine aventure commence ici.",
  "cuentaP1": "Forfait local et préférences",
  "cuentaP2": "Accès direct à vos forfaits",
  "cuentaP3": "Aucun paiement dans cette démo",
  "tituloDestino": "Destination — KAVARI Travel",
  "seleccionarPais": "Pays",
  "buscarPais": "Rechercher un pays…",
  "heroSubtitulo": "avec KAVARI",
  "scrollDesplazar": "Défiler",
  "quoteInicio": "Voyager est le seul investissement qui vous rend plus riche.",
  "lugaresDesc": "Découvrez les lieux qui définissent chaque coin du monde.",
  "aventuraTag": "Nature · Adrénaline",
  "guiasTituloHeader": "Guides touristiques",
  "guiasDescHeader": "Connectez-vous avec des experts locaux certifiés qui connaissent chaque coin de la destination.",
  "modalCerrar": "Fermer",
  "verEnGoogleMaps": "Voir sur Google Maps",
  "tituloIndex": "KAVARI Travel — Découvrez le monde",
  "heroDescripcion": "Vivez des expériences inoubliables à travers le monde.",
  "searchTitulo": "Prêt pour votre prochaine aventure ?",
  "searchBoton": "Commencer maintenant",
  "top10Titulo": "Top 10 des lieux les plus visités",
  "paquetesTitulo": "Forfaits de voyage",
  "planCtaTitulo": "Demandez votre forfait de voyage",
  "planCtaNombreLabel": "Nom complet",
  "planCtaEmailLabel": "Adresse e-mail",
  "planCtaEmailPH": "vous@email.com",
  "planCtaTelefonoLabel": "Téléphone",
  "planCtaDestinoLabel": "Destination souhaitée",
  "planCtaDestinoOpc": "Sélectionnez une destination",
  "planCtaFechaLabel": "Date de voyage",
  "planCtaPresupuestoLabel": "Budget estimé par personne (USD)",
  "planCtaPresupuestoOpc": "Sélectionnez une fourchette",
  "planCtaMensajeLabel": "Parlez-nous de votre voyage (facultatif)",
  "planCtaBoton": "Envoyer la demande",
  "tituloPaises": "KAVARI – Explorez 21 destinations en Amérique latine et dans les Caraïbes",
  "paisesEyebrow": "Votre prochaine aventure vous attend",
  "paisesTitulo": "Explorez nos destinations",
  "paisesBuscar": "Recherchez votre destination avec Kavari…",
  "paisesDestinos": "destinations",
  "paisesCargando": "Chargement des destinations...",
  "tituloPerfil": "Mon profil · KAVARI",
  "perfilAuthDesc": "Accédez à votre compte pour gérer vos informations et préférences de voyage.",
  "perfilOtpLink": "Envoyer le code de vérification par e-mail",
  "perfilOtpEmailLabel": "Adresse e-mail",
  "perfilOtpCodeLabel": "Code de vérification",
  "perfilNoCuenta": "Vous n'avez pas de compte ?",
  "perfilCrearCuenta": "Créer un compte",
  "perfilRegistroTitulo": "Créez votre compte KAVARI",
  "perfilYaCuenta": "Vous avez déjà un compte ?",
  "perfilTabInfo": "Informations personnelles",
  "perfilTabViaje": "Préférences de voyage",
  "perfilTabConfig": "Paramètres",
  "perfilFechaNacimiento": "Date de naissance",
  "perfilPaisResidencia": "Pays de résidence",
  "perfilDestinosInteres": "Destinations souhaitées",
  "perfilPresupuesto": "Budget mensuel de voyage",
  "perfilEstiloViaje": "Style de voyage",
  "perfilIdiomasViaje": "Langues que vous parlez",
  "perfilFavoritosDrag": "Faites glisser les cartes pour changer l'ordre",
  "perfilFavoritosSortLabel": "Trier par",
  "perfilFavoritosSortAlpha": "Alphabétique",
  "perfilFavoritosSortRecent": "Le plus récent",
  "perfilFavoritosExplorar": "Explorer les destinations",
  "perfilConfigCuenta": "Compte",
  "perfilConfigEmail": "Adresse e-mail",
  "perfilConfigPlan": "Forfait actuel",
  "perfilConfigPreferencias": "Préférences",
  "perfilConfigIdioma": "Langue",
  "perfilConfigTema": "Mode sombre",
  "perfilConfigZona": "Zone dangereuse",
  "tituloPlanes": "Forfaits · KAVARI",
  "planesTitulo": "Choisissez comment vous voulez<br>voyager avec KAVARI.",
  "planViajeroPrecio": "Gratuit",
  "planViajeroDuracion": "pour toujours",
  "planViajeroDesc": "La façon simple de découvrir le monde avec KAVARI.",
  "planViajeroF1": "21 destinations",
  "planViajeroF3": "Assistant KAVARI",
  "planPremiumBadge": "Le plus choisi",
  "planPremiumDesc": "Pour ceux qui veulent préparer chaque détail de leur prochain voyage.",
  "planPremiumCta": "Choisir Premium",
  "planPremiumF3": "Préférences de voyage enregistrées",
  "planOpCta": "Choisir OP",
  "planOpF1": "Tout dans Premium",
  "planOpF2": "Itinéraires prioritaires",
  "planOpF4": "Support prioritaire",
  "tituloSobrenosotros": "À propos — KAVARI",
  "aboutEyebrow": "À propos",
  "aboutQueEs": "Qu'est-ce que KAVARI ?",
  "aboutStatDestinos": "Destinations",
  "aboutStatEquipo": "Membres",
  "aboutStatFundacion": "Fondation",
  "aboutMisionLabel": "Notre mission",
  "aboutMision": "Mission",
  "aboutVisionLabel": "Notre vision",
  "aboutVision": "Vision",
  "aboutEquipo": "Notre équipe",
  "aboutEquipoDesc": "Les personnes qui rendent KAVARI possible, avec dévouement et esprit d'équipe.",
  "aboutControl": "Contrôle produit",
  "aboutGestion": "Gestion",
  "aboutDesarrollo": "Développement",
  "cargandoGuias": "Chargement des guides…",
  "filtroTodos": "Tous",
  "contactGuide": "Contacter le guide",
  "sinGuias": "Aucun guide disponible pour cette destination",
  "guiaDisponible": "Guide disponible",
  "guiaNoDisponible": "Guide non disponible",
  "contratar": "Embaucher",
  "precioHora": "par heure",
  "aerolineasNoDisponible": "Aucune compagnie aérienne disponible pour cette destination",
  "reservarVuelo": "Réserver un vol",
  "zonaLabel": "Zone",
  "cargandoTiendas": "Chargement des boutiques…",
  "souvenirsTiendasLabel": "boutiques",
  "souvenirsProductosLabel": "produits",
  "destinosDestacadosEn": "Destinations vedettes dans",
  "explorarMas": "Explorer plus",
  "culturaDarkBandTag": "Identité · Tradition",
  "destinosImprescindiblesEn": "Destinations incontournables dans",
  "aventuraDarkBandTag": "Nature · Adrénaline",
  "cuandoViajar": "Quand partir",
  "horarioLabel": "Horaires",
  "consejoLabel": "Conseil",
  "cuentaHola": "Bonjour, {name}",
  "cuentaActiva": "Votre compte est actif sur ce navigateur.",
  "cuentaPasajero": "Passager",
  "cuentaCorreo": "E-mail",
  "cuentaGestionar": "Gérer le forfait →",
  "cuentaUnete": "Rejoindre KAVARI",
  "cuentaInicia": "Se connecter",
  "cuentaCreaDesc": "Créez un compte local pour conserver votre forfait.",
  "cuentaCrearTab": "Créer un compte",
  "cuentaIngresarTab": "Se connecter",
  "ayudaCopiado": "Copié !",
  "ayudaResultados": "questions trouvées",
  "guideRequeridos": "Tous les champs sont obligatoires",
  "guideCorreoInvalido": "Saisissez une adresse e-mail valide",
  "guideAceptaTerminos": "Vous devez accepter les conditions générales",
  "guideProcesando": "Traitement de votre inscription...",
  "guideSubiendoDocs": "Téléchargement des documents...",
  "guideExito": "Inscription réussie ! Nous vous contacterons par e-mail pour activer votre profil."
};
