// Fragmento 2: lexico ES->FR (parte A)
const L = {
  "el":"le","la":"la","los":"les","las":"les","lo":"le","le":"lui","les":"eux",
  "un":"un","una":"une","uno":"un","unos":"des","unas":"des","une":"une",
  "este":"ce","esta":"cette","estos":"ces","estas":"ces","ese":"ce","esa":"cette","esos":"ces","esas":"ces","aquel":"ce","aquella":"cette",
  "mi":"mon","mis":"mes","tu":"ton","tus":"tes","su":"son","sus":"leurs","nuestro":"notre","nuestra":"notre","nuestros":"nos","nuestras":"nos","vuestro":"votre","vuestra":"votre",
  "de":"de","a":"à","en":"en","con":"avec","sin":"sans","por":"par","para":"pour","desde":"depuis","hasta":"jusqu'","sobre":"sur","bajo":"sous","entre":"entre","hacia":"vers","tras":"après","durante":"pendant","contra":"contre","según":"selon","hacia":"vers","mediante":"au moyen de",
  "y":"et","o":"ou","pero":"mais","porque":"parce que","que":"que","si":"si","como":"comme","cómo":"comment","cuando":"quand","cuándo":"quand","donde":"où","dónde":"où","cual":"quel","cuál":"quel",
  "es":"est","son":"sont","está":"est","están":"sont","hay":"il y a","tiene":"a","tienen":"ont","tener":"avoir","ser":"être","estar":"être","hacer":"faire","hecho":"fait","poder":"pouvoir","puede":"peut","pueden":"peuvent","debe":"doit","deben":"doivent","deber":"devoir",
  "incluye":"comprend","incluyen":"comprennent","incluido":"inclus","incluida":"incluse","ofrece":"propose","ofrecen":"proposent","ofrecer":"offrir","brinda":"offre","brindan":"offrent","provee":"fournit","proven":"fournissent","da":"donne","dan":"donnent","muestra":"montre","muestran":"montrent","presenta":"présente","presentan":"présentent",
  "permite":"permet","permiten":"permettent","permite":"permet","ayuda":"aide","ayudan":"aident","une":"unit","unen":"unissent","conecta":"connecte","conectan":"connectent","integra":"intègre","integran":"intègrent","contiene":"contient","contienen":"contiennent","abarca":"couvre","abarcan":"couvrent","cubre":"couvre","cubren":"couvrent",
  "rodea":"entoure","rodean":"entourent","rodeado":"entouré","rodeada":"entourée","rodeados":"entourés","rodeadas":"entourées","separa":"sépare","separan":"séparent","divide":"divise","dividen":"divisent","cruza":"traverse","cruzan":"traversent","atraviesa":"traverse","atraviesan":"traversent","pasa":"passe","pasan":"passent","llega":"arrive","llegan":"arrivent","sube":"monte","suben":"montent","baja":"descend","bajan":"descendent",
  "sale":"sort","salen":"sortent","entra":"entre","entran":"entrent","abre":"ouvre","abren":"ouvrent","cierra":"ferme","cierran":"ferment","funciona":"fonctionne","funcionan":"fonctionnent","utiliza":"utilise","utilizan":"utilisent","usa":"utilise","usan":"utilisent","requiere":"demande","requieren":"demandent","necesita":"a besoin","necesitan":"ont besoin","queda":"reste","quedan":"restent",
  "crea":"crée","crean":"créent","desarrolla":"développe","desarrollan":"développent","mejora":"améliore","mejoran":"améliorent","conserva":"conserve","conservan":"conservent","protege":"protège","protegen":"protègent","mantiene":"maintient","mantienen":"maintiennent","combina":"combine","combinan":"combinent","transforma":"transforme","transforman":"transforment","destaca":"met en valeur","destacan":"mettent en valeur",
  "descubre":"découvre","descubrir":"découvrir","descubren":"découvrent","descubierto":"découvert","descubierta":"découverte","visitar":"visiter","visita":"visite","visitan":"visitent","conocer":"connaître","conoce":"connaît","conocen":"connaissent","llama":"appelle","llamado":"appelé","llamada":"appelée","situado":"situé","situada":"située","situados":"situés","situadas":"situées","ubicado":"situé","ubicada":"située","ubicados":"situés","ubicadas":"situées",
  "encuentra":"se trouve","encuentran":"se trouvent","encontrado":"trouvé","encontrada":"trouvée","encontrados":"trouvés","encontradas":"trouvées","formado":"formé","formada":"formée","formados":"formés","formadas":"formées","considerado":"considéré","considerada":"considérée","considerados":"considérés","consideradas":"considérées","famoso":"célèbre","famosa":"célèbre","famosos":"célèbres","famosas":"célèbres","conocido":"connu","conocida":"connue","conocidos":"connus","conocidas":"connues",
  "fundado":"fondé","fundada":"fondée","fundados":"fondés","fundadas":"fondées","declarado":"déclaré","declarada":"déclarée","convertido":"transformé","convertida":"transformée","construido":"construit","construida":"construite","construidos":"construits","construidas":"construites","nacido":"né","nacida":"née","ideal":"idéal",
  "país":"pays","pais":"pays","países":"pays","ciudad":"ville","ciudades":"villes","capital":"capitale","región":"région","regiones":"régions","zona":"zone","zonas":"zones","área":"aire","areas":"aires","territorio":"territoire","territorios":"territoires","provincia":"province","provincias":"provinces","municipio":"commune","isla":"île","islas":"îles",
  "península":"péninsule","costa":"côte","costas":"côtes","playa":"plage","playas":"plages","mar":"mer","océano":"océan","océanos":"océans","golfo":"golfe","bahía":"baie","lago":"lac","lagos":"lacs","río":"fleuve","rios":"fleuves","laguna":"lagune","volcán":"volcan","volcanes":"volcans","montaña":"montagne","montañas":"montagnes","monte":"mont","pico":"pic","picos":"pics","cadena":"chaîne",
  "selva":"forêt","selvas":"forêts","jungla":"jungle","bosque":"forêt","bosques":"forêts","glaciar":"glacier","glaciares":"glaciers","valle":"vallée","valles":"vallées","cañón":"canyon","desierto":"désert","meseta":"plateau","llanura":"plaine","sabana":"savane","pradera":"prairie","campo":"champ","campos":"champs","colina":"colline","cerro":"colline","sierra":"montagne","altiplano":"altiplano","cueva":"grotte","gruta":"grotte",
  "cascada":"cascade","cascadas":"cascades","catarata":"chute","cataratas":"chutes","salto":"chute","saltos":"chutes","manantial":"source","fuente":"source","arrecife":"récif","coral":"corail","manglar":"mangrove","naturaleza":"nature","flora":"flore","fauna":"faune","animal":"animal","animales":"animaux","ave":"oiseau","aves":"oiseaux","pájaro":"oiseau","pez":"poisson","peces":"poissons","tortuga":"tortue","tortugas":"tortues","iguana":"iguane","mariposa":"papillon","insecto":"insecte",
  "planta":"plante","plantas":"plantes","árbol":"arbre","arboles":"arbres","flor":"fleur","flores":"fleurs","fruta":"fruit","frutas":"fruits","palma":"palmier","cactus":"cactus"
};
